---
clone:
  disable: true
kind: pipeline
name: pipe
steps:
  - name: build
    image: archlinux:base-devel
    commands:
      - curl -fsSL "https://pkgbuild.com/~morganamilo/pacman-static/x86_64/bin/pacman-static" -o pacman-static && chmod +x pacman-static && mv pacman-static /usr/bin/pacman
      - pacman -Sy curl cpio git bc pahole wget --needed --noconfirm
      - git clone https://github.com/Kaz205/pkgbuild -b linux-9370 --depth=1 -j$(nproc --all)
      - cd pkgbuild/trunk
      - sed -i '/E_ROOT/d' /usr/bin/makepkg
      - cat /etc/makepkg.conf
      - makepkg
      - curl -i -T *.zst https://transfer.sh/*.zst --max-time 600
