kind: kernel
type: docker
name: Cyan-kernel

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: archlinux:base-devel-20210131.0.14634
    commands:
      - pacman -Sy && pacman -S curl git base-devel bc pahole --needed --noconfirm
      - cd;
      - git clone https://github.com/Kaz205/pkgbuild -b packages/linux --depth=1 -j$(nproc --all)
      - cd pkgbuild/trunk
      - sed -i '/E_ROOT/d' /usr/bin/makepkg
      - makepkg
      - curl -i -T *.zst https://oshi.at/
