version: 2.1
jobs:
  compile:
   docker:
      - image: archlinux:base-devel
   steps:
      - run:
          command: |
           curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
           pacman -Sy && pacman -S git bc pahole cpio --needed --noconfirm
           cd;
           git clone https://github.com/Kaz205/linux -b rpi-5.12.y --depth=1 -j$(nproc --all)
           git clone https://github.com/Kaz205/arm-none-eabi-gcc -b master --depth=1 -j$(nproc --all)
           git clone https://github.com/Kaz205/aarch64-linux-gnu-gcc -b master --depth=1 -j$(nproc --all)
           export CROSS_COMPILE=$HOME/aarch64-linux-gnu-gcc/bin/aarch64-linux-gnu-
           export CROSS_COMPILE_ARM32=$HOME/arm-none-eabi-gcc/bin/arm-none-eabi-
           cd linux
           make bcm2711_defconfig -j$(nproc --all)
           make Image dtbs -j$(nproc --all)
           mkdir $HOME/out
           cp arch/arm64/boot/Image $HOME/out
           cp arch/arm/boot/dts/*.dtb $HOME/out/dts
           cp arch/arm/boot/dts/overlays/*.dtb* $HOME/out/overlays/

      - store_artifacts:
          path: $HOME/out
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
